// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPoint struct {
	Point     string `json:"point"`
	Timestamp string `json:"timestamp"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Point struct {
	Point string `json:"point"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
